In [47]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.model_selection import KFold

from functools import reduce
from astral import moon

In [48]:
# Definimos los archivos CSV
archivo_lluvia = './Dataset_INUMET/CSV/Lluvia.csv'
archivo_temperatura = './Dataset_INUMET/CSV/Temperatura.csv'
archivo_humedad = './Dataset_INUMET/CSV/Humedad.csv'
archivo_viento = './Dataset_INUMET/CSV/VientoCarrasco.csv'
archivo_fenomenos = './Dataset_INUMET/CSV/Fenomenos.csv'

# Los cargamos en dataframes
try:
    lluvia_df = pd.read_csv(archivo_lluvia, sep=';')
    temperatura_df = pd.read_csv(archivo_temperatura, sep=';')
    humedad_df = pd.read_csv(archivo_humedad, sep=';')
    viento_df = pd.read_csv(archivo_viento, sep=';')
    fenomenos_df = pd.read_csv(archivo_fenomenos, sep=';')
except Exception as e:
    print(f"Error al leer el archivo CSV: {e}")
    exit()

In [49]:
## Analisis preliminar de los datos
# Debemos determinar el rango de fechas que vamos a utilizar para dataset final
# Para ello, obtenemos la fecha minima y maxima de cada dataframe, que se corresponde con la primer y ultima fila no nula
fechas = {
    'lluvia': (lluvia_df.iloc[0, 2], lluvia_df.iloc[lluvia_df.last_valid_index(), 2]),
    'temperatura': (temperatura_df.iloc[0, 0], temperatura_df.iloc[temperatura_df.last_valid_index(), 0]),
    'humedad': (humedad_df.iloc[0, 0], humedad_df.iloc[humedad_df.last_valid_index(), 0]),
    'viento': (viento_df.iloc[0, 0], viento_df.iloc[viento_df.last_valid_index(), 0]),
    'fenomenos': (fenomenos_df.iloc[0, 0], fenomenos_df.iloc[fenomenos_df.last_valid_index(), 0])
}
# Imprimimos las fechas para ver el rango de cada dataframe
for key in fechas:
    print(f"{key}: {fechas[key][0]} - {fechas[key][1]}")
# Definimos el rango a partir de los datos y nuestras consideraciones (en el informe se explica)
rango = (pd.to_datetime(humedad_df.iloc[0, 0], format='%d/%m/%Y'), pd.to_datetime(lluvia_df.iloc[lluvia_df.last_valid_index() - 1, 2], format='%d/%m/%Y'))
print(f"Rango definido: {rango[0]} - {rango[1]}")

lluvia: 1/1/1950 - 31/7/2025
temperatura: 1/1/1970 - 7/8/2025
humedad: 1/1/1980 - 8/8/2025 23:00
viento: 7/7/1986 08:00 - 8/8/2025 11:00
fenomenos: 1/1/2000 - 11/8/2025 23:00
Rango definido: 1980-01-01 00:00:00 - 2025-07-30 00:00:00

In [50]:
## Lluvias
# Nos quedamos con las filas dentro del rango definido
lluvia_df_subset = lluvia_df[(pd.to_datetime(lluvia_df.iloc[:, 2], format='%d/%m/%Y') >= rango[0])].copy()
lluvia_df_subset.reset_index(drop=True, inplace=True)
# Nos quedamos solamente con las columnas de la fecha y los mm de lluvia
lluvia_df_subset = lluvia_df_subset.iloc[:, [2, 3]]
lluvia_df_subset.columns = ['fecha', 'mm_lluvia']
# Normalizamos el formato de la fecha (pasamos a pandas datetime64[ns])
lluvia_df_subset['fecha'] = pd.to_datetime(lluvia_df_subset['fecha'], format='%d/%m/%Y')
# Verificamos si hay valores no numéricos en lluvia y los reemplazamos por 0, por lo que comentó el profe. Esto se puede hacer para todo el dataset porque reemplazamos por valor constante.
lluvia_df_subset['mm_lluvia'] = pd.to_numeric(lluvia_df_subset['mm_lluvia'], errors='coerce').fillna(0)
# Definimos día lluvioso como los días con lluvias mayores a 1mm
umbral_lluvia = 1.0
# Creamos la columna "día lluvioso" (nd = 1)
lluvia_df_subset['dia_lluvioso'] = (lluvia_df_subset['mm_lluvia'] >= umbral_lluvia).astype(int)
# Creamos la columna "semana lluviosa" (nd = 7), que indica la cantidad de días lluviosos en los últimos 7 días (incluyendo el día actual)
lluvia_df_subset['semana_lluviosa'] = lluvia_df_subset['dia_lluvioso'].rolling(window=7, min_periods=1).sum().astype(int)
# Creamos la columna "quincena lluviosa" (nd = 15), que indica la cantidad de días lluviosos en los últimos 15 días (incluyendo el día actual)
lluvia_df_subset['quincena_lluviosa'] = lluvia_df_subset['dia_lluvioso'].rolling(window=15, min_periods=1).sum().astype(int)
# Creamos la columna "mes lluvioso" (nd = 30), que indica la cantidad de días lluviosos en los últimos 30 días (incluyendo el día actual)
lluvia_df_subset['mes_lluvioso'] = lluvia_df_subset['dia_lluvioso'].rolling(window=30, min_periods=1).sum().astype(int)

# Creamos la clase objetivo "mañana llueve"
lluvia_df_subset['manana_llueve'] = lluvia_df_subset['dia_lluvioso'].shift(-1)
# Eliminamos la última fila que ahora tiene un valor NaN en 'manana_llueve'
lluvia_df_subset = lluvia_df_subset.dropna(subset=['manana_llueve'])
lluvia_df_subset['manana_llueve'] = lluvia_df_subset['manana_llueve'].astype(int)

print(lluvia_df_subset.head(5))
print(lluvia_df_subset.tail(5))
print("----")
print(lluvia_df_subset.dtypes)

       fecha  mm_lluvia  dia_lluvioso  semana_lluviosa  quincena_lluviosa  \
0 1980-01-01        0.0             0                0                  0
1 1980-01-02        0.0             0                0                  0
2 1980-01-03        0.0             0                0                  0
3 1980-01-04        0.0             0                0                  0
4 1980-01-05       12.4             1                1                  1

   mes_lluvioso  manana_llueve
0             0              0
1             0              0
2             0              0
3             0              1
4             1              0
           fecha  mm_lluvia  dia_lluvioso  semana_lluviosa  quincena_lluviosa  \
16643 2025-07-26        0.0             0                1                  2
16644 2025-07-27        0.0             0                1                  2
16645 2025-07-28        0.0             0                1                  2
16646 2025-07-29        0.0             0                1                  2
16647 2025-07-30        0.0             0                1                  2

       mes_lluvioso  manana_llueve
16643             3              0
16644             3              0
16645             3              0
16646             2              0
16647             2              0
----
fecha                datetime64[ns]
mm_lluvia                   float64
dia_lluvioso                  int64
semana_lluviosa               int64
quincena_lluviosa             int64
mes_lluvioso                  int64
manana_llueve                 int64
dtype: object

In [51]:
## Temperatura
# Nos quedamos con las filas dentro del rango definido
temperatura_df_subset = temperatura_df[(pd.to_datetime(temperatura_df.iloc[:, 0], format='%d/%m/%Y') >= rango[0]) & (pd.to_datetime(temperatura_df.iloc[:, 0], format='%d/%m/%Y') <= rango[1])].copy()
temperatura_df_subset.reset_index(drop=True, inplace=True)
# Nos quedamos solamente con las columnas fecha, Tmax y Tmin de Carrasco
temperatura_df_subset = temperatura_df_subset.iloc[:, :3]
temperatura_df_subset.columns = ['fecha', 'temp_max', 'temp_min']
# Normalizamos el formato de la fecha (pasamos a pandas datetime64[ns])
temperatura_df_subset['fecha'] = pd.to_datetime(temperatura_df_subset['fecha'], format='%d/%m/%Y', errors='coerce')
# Eliminamos filas con fechas inválidas
temperatura_df_subset = temperatura_df_subset.dropna(subset=['fecha'])

# Creamos columnas temp_max_semana, temp_min_semana con el promedio de la semana anterior (nd = 7)
temperatura_df_subset['temp_max_semana'] = temperatura_df_subset['temp_max'].rolling(window=7, min_periods=1).mean()
temperatura_df_subset['temp_min_semana'] = temperatura_df_subset['temp_min'].rolling(window=7, min_periods=1).mean()
# Creamos columnas temp_max_quincena, temp_min_quincena con el promedio de los últimos 15 días (nd = 15)
temperatura_df_subset['temp_max_quincena'] = temperatura_df_subset['temp_max'].rolling(window=15, min_periods=1).mean()
temperatura_df_subset['temp_min_quincena'] = temperatura_df_subset['temp_min'].rolling(window=15, min_periods=1).mean()
# Creamos columnas temp_max_mes, temp_min_mes con el promedio del último mes (nd = 30)
temperatura_df_subset['temp_max_mes'] = temperatura_df_subset['temp_max'].rolling(window=30, min_periods=1).mean()
temperatura_df_subset['temp_min_mes'] = temperatura_df_subset['temp_min'].rolling(window=30, min_periods=1).mean()

# Para categorizar hay que considerar antes valores de todo el dataset. Para hacerlo correctamente primero debemos separar en conjunto de entrenamiento y prueba.
# Se hace más adelante.

print(temperatura_df_subset.head(5))
print(temperatura_df_subset.tail(5))
print("----")
print(temperatura_df_subset.dtypes)

       fecha  temp_max  temp_min  temp_max_semana  temp_min_semana  \
0 1980-01-01      20.0      16.0        20.000000        16.000000
1 1980-01-02      26.2      10.7        23.100000        13.350000
2 1980-01-03      28.4      15.2        24.866667        13.966667
3 1980-01-04      27.2      16.8        25.450000        14.675000
4 1980-01-05      29.0      15.6        26.160000        14.860000

   temp_max_quincena  temp_min_quincena  temp_max_mes  temp_min_mes
0          20.000000          16.000000     20.000000     16.000000
1          23.100000          13.350000     23.100000     13.350000
2          24.866667          13.966667     24.866667     13.966667
3          25.450000          14.675000     25.450000     14.675000
4          26.160000          14.860000     26.160000     14.860000
           fecha  temp_max  temp_min  temp_max_semana  temp_min_semana  \
16643 2025-07-26      13.2       8.8        15.000000         6.900000
16644 2025-07-27      12.6       9.0        14.085714         7.500000
16645 2025-07-28      13.3       9.9        13.328571         7.885714
16646 2025-07-29      15.0       2.2        13.814286         7.200000
16647 2025-07-30      18.7       4.8        14.871429         6.771429

       temp_max_quincena  temp_min_quincena  temp_max_mes  temp_min_mes
16643          15.086667           6.686667     14.540000      5.203333
16644          15.240000           7.073333     14.480000      5.456667
16645          15.300000           7.453333     14.510000      5.763333
16646          15.320000           7.200000     14.663333      5.656667
16647          15.073333           6.960000     15.020000      5.716667
----
fecha                datetime64[ns]
temp_max                    float64
temp_min                    float64
temp_max_semana             float64
temp_min_semana             float64
temp_max_quincena           float64
temp_min_quincena           float64
temp_max_mes                float64
temp_min_mes                float64
dtype: object

In [52]:
## Humedad
# Nos quedamos con las filas dentro del rango definido
humedad_df_subset = humedad_df[(pd.to_datetime(humedad_df.iloc[:, 0], format='%d/%m/%Y %H:%M', errors='coerce') >= rango[0]) & (pd.to_datetime(humedad_df.iloc[:, 0], format='%d/%m/%Y %H:%M', errors='coerce') <= rango[1])].copy()
humedad_df_subset.reset_index(drop=True, inplace=True)
# Nos quedamos solamente con las columnas de la fecha y la humedad relativa de Carrasco
humedad_df_subset = humedad_df_subset.iloc[:,:2].copy()
humedad_df_subset.columns = ['fecha', 'humedad_relativa']
# Normalizamos el formato de la fecha (pasamos a pandas datetime64[ns]), forzando errores a NaT
humedad_df_subset['fecha'] = pd.to_datetime(humedad_df_subset['fecha'], format='%d/%m/%Y %H:%M', errors='coerce')
# Eliminamos filas con fechas no válidas
humedad_df_subset = humedad_df_subset.dropna(subset=['fecha'])
# Transformamos la fecha a solo fecha (sin hora) y lo devolvemos a datetime64[ns] para ser consistentes
humedad_df_subset['fecha'] = humedad_df_subset['fecha'].dt.date
humedad_df_subset['fecha'] = pd.to_datetime(humedad_df_subset['fecha'])
# Agrupamos por dia y calculamos la humedad relativa promedio diaria
humedad_df_subset = humedad_df_subset.groupby('fecha').agg({'humedad_relativa': 'mean'}).reset_index()

# Creamos la columna humedad_relativa_semana con el promedio de la semana anterior (nd = 7)
humedad_df_subset['humedad_relativa_semana'] = humedad_df_subset['humedad_relativa'].rolling(window=7, min_periods=1).mean()
# Creamos la columna humedad_relativa_quincena con el promedio de los últimos 15 días (nd = 15)
humedad_df_subset['humedad_relativa_quincena'] = humedad_df_subset['humedad_relativa'].rolling(window=15, min_periods=1).mean()
# Creamos la columna humedad_relativa_mes con el promedio del último mes (nd = 30)
humedad_df_subset['humedad_relativa_mes'] = humedad_df_subset['humedad_relativa'].rolling(window=30, min_periods=1).mean()


# Para categorizar hay que considerar antes valores de todo el dataset. Para hacerlo correctamente primero debemos separar en conjunto de entrenamiento y prueba.
# Se hace más adelante.

print(humedad_df_subset.head(5))
print(humedad_df_subset.tail(5))
print("----")
print(humedad_df_subset.dtypes)

       fecha  humedad_relativa  humedad_relativa_semana  \
0 1980-01-01         64.857143                64.857143
1 1980-01-02         67.428571                66.142857
2 1980-01-03         61.714286                64.666667
3 1980-01-04         63.285714                64.321429
4 1980-01-05         46.142857                60.685714

   humedad_relativa_quincena  humedad_relativa_mes
0                  64.857143             64.857143
1                  66.142857             66.142857
2                  64.666667             64.666667
3                  64.321429             64.321429
4                  60.685714             60.685714
           fecha  humedad_relativa  humedad_relativa_semana  \
16642 2025-07-25         92.434783                84.383682
16643 2025-07-26         83.478261                84.340203
16644 2025-07-27         84.391304                84.142857
16645 2025-07-28         88.086957                84.360248
16646 2025-07-29         86.391304                83.695652

       humedad_relativa_quincena  humedad_relativa_mes
16642                  89.118182             85.978195
16643                  88.709486             86.382543
16644                  87.700791             86.785441
16645                  87.080501             86.982543
16646                  86.321080             87.240514
----
fecha                        datetime64[ns]
humedad_relativa                    float64
humedad_relativa_semana             float64
humedad_relativa_quincena           float64
humedad_relativa_mes                float64
dtype: object

In [53]:
## Viento
# Nos quedamos con las filas dentro del rango definido
viento_df_subset = viento_df[(pd.to_datetime(viento_df.iloc[:, 0], format='%d/%m/%Y %H:%M', errors='coerce') >= rango[0]) & (pd.to_datetime(viento_df.iloc[:, 0], format='%d/%m/%Y %H:%M', errors='coerce') <= rango[1])].copy()
viento_df_subset.reset_index(drop=True, inplace=True)
# Nos quedamos solamente con las columnas de la fecha y la dirección del viento de Carrasco
viento_df_subset = viento_df_subset.iloc[:, :2].copy()
viento_df_subset.columns = ['fecha', 'direccion_viento']
# Normalizamos el formato de la fecha (pasamos a pandas datetime64[ns]), forzando errores a NaT
viento_df_subset['fecha'] = pd.to_datetime(viento_df_subset['fecha'], format='%d/%m/%Y %H:%M', errors='coerce')
# Eliminamos filas con fechas no válidas
viento_df_subset = viento_df_subset.dropna(subset=['fecha'])
# Transformamos la fecha a solo fecha (sin hora) y lo devolvemos a datetime64[ns] para ser consistentes
viento_df_subset['fecha'] = viento_df_subset['fecha'].dt.date
viento_df_subset['fecha'] = pd.to_datetime(viento_df_subset['fecha'])
# Creamos funcion para categorizar la dirección del viento de grados a una de las 8 direcciones
def categorizar_direccion_viento(grados):
    if grados is None or pd.isna(grados):
        return np.nan
    try:
        grados = float(grados)
    except (ValueError, TypeError):
        return np.nan
    dirs = [0, 1, 2, 3, 4, 5, 6, 7]
    #dirs = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW']
    ix = round(grados / 45) % 8
    return dirs[ix] 
# La aplicamos al dataframe
viento_df_subset['direccion_viento'] = viento_df_subset['direccion_viento'].apply(categorizar_direccion_viento)
# Una vez categorizado, agrupamos por dia y calculamos la dirección del viento predominante diaria
viento_df_subset = viento_df_subset.groupby('fecha').agg({'direccion_viento': lambda x: x.mode()[0] if not x.mode().empty else np.nan}).reset_index()

# Estos atributos no tienen mucho sentido por si mismos, pero para ser consistentes con el resto del dataset los incluimos.
# Creamos la columna direccion_viento_semana con la moda de la semana anterior (nd = 7). Usamos groupby porque es categórica
viento_df_subset['direccion_viento_semana'] = viento_df_subset['direccion_viento'].rolling(window=7, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
# Creamos la columna direccion_viento_quincena con la moda de los últimos 15 días (nd = 15)
viento_df_subset['direccion_viento_quincena'] = viento_df_subset['direccion_viento'].rolling(window=15, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
# Creamos la columna direccion_viento_mes con la moda del último mes (nd = 30)
viento_df_subset['direccion_viento_mes'] = viento_df_subset['direccion_viento'].rolling(window=30, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)

# Pasamos las columnas de dirección del viento de [0, 1, 2, 3, 4, 5, 6, 7] a tipo category con ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW']
viento_df_subset['direccion_viento'] = viento_df_subset['direccion_viento'].map({0: 'N', 1: 'NE', 2: 'E', 3: 'SE', 4: 'S', 5: 'SW', 6: 'W', 7: 'NW'}).astype('category')
viento_df_subset['direccion_viento_semana'] = viento_df_subset['direccion_viento_semana'].map({0: 'N', 1: 'NE', 2: 'E', 3: 'SE', 4: 'S', 5: 'SW', 6: 'W', 7: 'NW'}).astype('category')
viento_df_subset['direccion_viento_quincena'] = viento_df_subset['direccion_viento_quincena'].map({0: 'N', 1: 'NE', 2: 'E', 3: 'SE', 4: 'S', 5: 'SW', 6: 'W', 7: 'NW'}).astype('category')
viento_df_subset['direccion_viento_mes'] = viento_df_subset['direccion_viento_mes'].map({0: 'N', 1: 'NE', 2: 'E', 3: 'SE', 4: 'S', 5: 'SW', 6: 'W', 7: 'NW'}).astype('category')


print(viento_df_subset.head(5))
print(viento_df_subset.tail(5))
print("----")
print(viento_df_subset.dtypes)

       fecha direccion_viento direccion_viento_semana  \
0 1986-07-07               NE                      NE
1 1986-07-08               NE                      NE
2 1986-07-09                N                      NE
3 1986-07-10                N                       N
4 1986-07-11                N                       N

  direccion_viento_quincena direccion_viento_mes
0                        NE                   NE
1                        NE                   NE
2                        NE                   NE
3                         N                    N
4                         N                    N
           fecha direccion_viento direccion_viento_semana  \
11568 2025-07-26                S                       S
11569 2025-07-27               SE                       S
11570 2025-07-28                S                       S
11571 2025-07-29               NW                      SE
11572 2025-07-30              NaN                       S

      direccion_viento_quincena direccion_viento_mes
11568                         S                    N
11569                         S                    N
11570                         S                    N
11571                         S                    N
11572                         S                    N
----
fecha                        datetime64[ns]
direccion_viento                   category
direccion_viento_semana            category
direccion_viento_quincena          category
direccion_viento_mes               category
dtype: object

In [54]:
## Fenómenos
# Nos quedamos con las filas dentro del rango definido
fenomenos_df_subset = fenomenos_df[(pd.to_datetime(fenomenos_df.iloc[:, 0], format='%d/%m/%Y', errors='coerce') >= rango[0]) & (pd.to_datetime(fenomenos_df.iloc[:, 0], format='%d/%m/%Y', errors='coerce') <= rango[1])].copy()
fenomenos_df_subset.reset_index(drop=True, inplace=True)
# Nos quedamos solamente con las columnas de la fecha y el fenómeno
fenomenos_df_subset = fenomenos_df_subset.iloc[:, :2].copy()
fenomenos_df_subset.columns = ['fecha', 'fenomeno']
# Normalizamos el formato de la fecha (pasamos a pandas datetime64[ns])
fenomenos_df_subset['fecha'] = pd.to_datetime(fenomenos_df_subset['fecha'], format='%d/%m/%Y', errors='coerce')
# Eliminamos filas con fechas no válidas
fenomenos_df_subset = fenomenos_df_subset.dropna(subset=['fecha'])
# Transformamos la fecha a solo fecha (sin hora) y lo devolvemos a datetime64[ns] para ser consistentes
fenomenos_df_subset['fecha'] = fenomenos_df_subset['fecha'].dt.date
fenomenos_df_subset['fecha'] = pd.to_datetime(fenomenos_df_subset['fecha'])
# Agrupamos por dia y marcamos si hubo tormenta con truenos (17) ese dia (1 si hubo, 0 si no)
fenomenos_df_subset['hay_truenos'] = fenomenos_df_subset['fenomeno'].apply(lambda x: 1 if x == 17 else 0)
fenomenos_df_subset = fenomenos_df_subset.groupby('fecha').agg({'hay_truenos': 'max'}).reset_index()

# Creamos la columna hay_truenos_semana con la cantidad de días con truenos en la semana anterior (nd = 7)
fenomenos_df_subset['hay_truenos_semana'] = fenomenos_df_subset['hay_truenos'].rolling(window=7, min_periods=1).sum().astype(int)
# Creamos la columna hay_truenos_quincena con la cantidad de días con truenos en los últimos 15 días (nd = 15)
fenomenos_df_subset['hay_truenos_quincena'] = fenomenos_df_subset['hay_truenos'].rolling(window=15, min_periods=1).sum().astype(int)
# Creamos la columna hay_truenos_mes con la cantidad de días con truenos en el último mes (nd = 30)
fenomenos_df_subset['hay_truenos_mes'] = fenomenos_df_subset['hay_truenos'].rolling(window=30, min_periods=1).sum().astype(int)

print(fenomenos_df_subset.head(5))
print(fenomenos_df_subset.tail(5))
print("----")
print(fenomenos_df_subset.dtypes)

       fecha  hay_truenos  hay_truenos_semana  hay_truenos_quincena  \
0 2000-01-01            0                   0                     0
1 2000-01-02            0                   0                     0
2 2000-01-03            0                   0                     0
3 2000-01-04            0                   0                     0
4 2000-01-05            0                   0                     0

   hay_truenos_mes
0                0
1                0
2                0
3                0
4                0
          fecha  hay_truenos  hay_truenos_semana  hay_truenos_quincena  \
9338 2025-07-26            0                   0                     0
9339 2025-07-27            0                   0                     0
9340 2025-07-28            0                   0                     0
9341 2025-07-29            0                   0                     0
9342 2025-07-30            0                   0                     0

      hay_truenos_mes
9338                0
9339                0
9340                0
9341                0
9342                0
----
fecha                   datetime64[ns]
hay_truenos                      int64
hay_truenos_semana               int64
hay_truenos_quincena             int64
hay_truenos_mes                  int64
dtype: object

In [55]:
## Estación
# Tomamos el dataframe con mayor cantidad de filas (lluvia) como base y nos quedamos con la columna fecha
estacion_df = lluvia_df_subset[['fecha']].copy()
# Creamos funcion para determinar la estación del año según la fecha
def determinar_estacion(fecha):
    mes = fecha.month
    dia = fecha.day
    if (mes == 12 and dia >= 21) or (mes <= 3 and (mes != 3 or dia < 20)):
        return 0
        # return 'Verano'
    elif (mes == 3 and dia >= 20) or (mes <= 6 and (mes != 6 or dia < 21)):
        return 1
        # return 'Otoño'
    elif (mes == 6 and dia >= 21) or (mes <= 9 and (mes != 9 or dia < 22)):
        return 2
        # return 'Invierno'
    else:
        return 3
        # return 'Primavera'
# Creamos la columna estación aplicando la función
estacion_df['estacion'] = estacion_df['fecha'].apply(determinar_estacion)
# Aseguramos que categoria sea de tipo category de pandas
estacion_df['estacion'] = estacion_df['estacion'].astype('category')

# Creamos columna estación_semana con la estación predominante en la semana anterior (nd = 7), la estacion es un categoría con string values
estacion_df['estacion_semana'] = estacion_df['estacion'].rolling(window=7, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
# Creamos columna estación_quincena con la estación predominante en los últimos 15 días (nd = 15)
estacion_df['estacion_quincena'] = estacion_df['estacion'].rolling(window=15, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
# Creamos columna estación_mes con la estación predominante en el último mes (nd = 30)
estacion_df['estacion_mes'] = estacion_df['estacion'].rolling(window=30, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)

# Pasamos las columnas de estación de [0, 1, 2, 3] a tipo category con ['Verano', 'Otoño', 'Invierno', 'Primavera']
estacion_df['estacion'] = estacion_df['estacion'].map({0: 'Verano', 1: 'Otoño', 2: 'Invierno', 3: 'Primavera'}).astype('category')
estacion_df['estacion_semana'] = estacion_df['estacion_semana'].map({0: 'Verano', 1: 'Otoño', 2: 'Invierno', 3: 'Primavera'}).astype('category')
estacion_df['estacion_quincena'] = estacion_df['estacion_quincena'].map({0: 'Verano', 1: 'Otoño', 2: 'Invierno', 3: 'Primavera'}).astype('category')
estacion_df['estacion_mes'] = estacion_df['estacion_mes'].map({0: 'Verano', 1: 'Otoño', 2: 'Invierno', 3: 'Primavera'}).astype('category')

print(estacion_df.head(5))
print(estacion_df.tail(5))
print("----")
print(estacion_df.dtypes)

       fecha estacion estacion_semana estacion_quincena estacion_mes
0 1980-01-01   Verano          Verano            Verano       Verano
1 1980-01-02   Verano          Verano            Verano       Verano
2 1980-01-03   Verano          Verano            Verano       Verano
3 1980-01-04   Verano          Verano            Verano       Verano
4 1980-01-05   Verano          Verano            Verano       Verano
           fecha  estacion estacion_semana estacion_quincena estacion_mes
16643 2025-07-26  Invierno        Invierno          Invierno     Invierno
16644 2025-07-27  Invierno        Invierno          Invierno     Invierno
16645 2025-07-28  Invierno        Invierno          Invierno     Invierno
16646 2025-07-29  Invierno        Invierno          Invierno     Invierno
16647 2025-07-30  Invierno        Invierno          Invierno     Invierno
----
fecha                datetime64[ns]
estacion                   category
estacion_semana            category
estacion_quincena          category
estacion_mes               category
dtype: object

In [56]:
## Fase lunar
# Tomamos el dataframe con mayor cantidad de filas (lluvia) como base y nos quedamos con la columna fecha
lunar_df = lluvia_df_subset[['fecha']].copy()
# Creamos funcion para determinar la fase lunar según la fecha
def determinar_fase_lunar(fecha):
    dia = moon.phase(fecha)

    if 0 <= dia <= 6:
        return 0
        # return "Luna Nueva"
    elif 7 <= dia <= 13:
        return 1
        # return "Cuarto Creciente"
    elif 14 <= dia <= 20:
        return 2
        # return "Luna Llena"
    else:  # 21–29
        return 3
        # return "Cuarto Menguante"

# Creamos la columna fase lunar aplicando la función
lunar_df['fase_lunar'] = lunar_df['fecha'].apply(determinar_fase_lunar)
# Aseguramos que categoria sea de tipo category de pandas
lunar_df['fase_lunar'] = lunar_df['fase_lunar'].astype('category')

# No vamos a usar este dato par el modelo principal, sino que para el extra, así que no calculamos otros nd. Además, la fase lunar cambia cada 7-8 días, por lo que no tendría sentido.

# Pasamos las columnas de fase lunar de [0, 1, 2, 3] a tipo category con ['Luna Nueva', 'Cuarto Creciente', 'Luna Llena', 'Cuarto Menguante']
lunar_df['fase_lunar'] = lunar_df['fase_lunar'].map({0: 'Luna Nueva', 1: 'Cuarto Creciente', 2: 'Luna Llena', 3: 'Cuarto Menguante'}).astype('category')

print(lunar_df.head(5))
print(lunar_df.tail(5))
print("----")
print(lunar_df.dtypes)

       fecha        fase_lunar
0 1980-01-01  Cuarto Menguante
1 1980-01-02        Luna Llena
2 1980-01-03        Luna Llena
3 1980-01-04        Luna Llena
4 1980-01-05        Luna Llena
           fecha  fase_lunar
16643 2025-07-26  Luna Nueva
16644 2025-07-27  Luna Nueva
16645 2025-07-28  Luna Nueva
16646 2025-07-29  Luna Nueva
16647 2025-07-30  Luna Nueva
----
fecha         datetime64[ns]
fase_lunar          category
dtype: object

In [57]:
## Merge de todos los dataframes
dataframes = [lluvia_df_subset, temperatura_df_subset, humedad_df_subset, viento_df_subset, fenomenos_df_subset, estacion_df, lunar_df]
merged_preliminar_df = reduce(lambda left, right: pd.merge(left, right, on='fecha', how='outer'), dataframes)
# Ordenamos por fecha
merged_preliminar_df = merged_preliminar_df.sort_values(by='fecha').reset_index(drop=True)

merged_preliminar_df

## Según el contador de dias de https://onlinealarmkur.com/date/es/
# Hay 27,617 días entre 01/01/1910 y 11/08/2025 (ambos inclusive), es la misma cantidad de filas que tenemos
# Por lo que no hay días faltantes en el dataset final

,fecha,mm_lluvia,dia_lluvioso,semana_lluviosa,quincena_lluviosa,mes_lluvioso,manana_llueve,temp_max,temp_min,temp_max_semana,...,direccion_viento_mes,hay_truenos,hay_truenos_semana,hay_truenos_quincena,hay_truenos_mes,estacion,estacion_semana,estacion_quincena,estacion_mes,fase_lunar
0,1980-01-01,0.0,0,0,0,0,0,20.0,16.0,20.000000,...,NaN,NaN,NaN,NaN,NaN,Verano,Verano,Verano,Verano,Cuarto Menguante
1,1980-01-02,0.0,0,0,0,0,0,26.2,10.7,23.100000,...,NaN,NaN,NaN,NaN,NaN,Verano,Verano,Verano,Verano,Luna Llena
2,1980-01-03,0.0,0,0,0,0,0,28.4,15.2,24.866667,...,NaN,NaN,NaN,NaN,NaN,Verano,Verano,Verano,Verano,Luna Llena
3,1980-01-04,0.0,0,0,0,0,1,27.2,16.8,25.450000,...,NaN,NaN,NaN,NaN,NaN,Verano,Verano,Verano,Verano,Luna Llena
4,1980-01-05,12.4,1,1,1,1,0,29.0,15.6,26.160000,...,NaN,NaN,NaN,NaN,NaN,Verano,Verano,Verano,Verano,Luna Llena
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16643,2025-07-26,0.0,0,1,2,3,0,13.2,8.8,15.000000,...,N,0.0,0.0,0.0,0.0,Invierno,Invierno,Invierno,Invierno,Luna Nueva
16644,2025-07-27,0.0,0,1,2,3,0,12.6,9.0,14.085714,...,N,0.0,0.0,0.0,0.0,Invierno,Invierno,Invierno,Invierno,Luna Nueva
16645,2025-07-28,0.0,0,1,2,3,0,13.3,9.9,13.328571,...,N,0.0,0.0,0.0,0.0,Invierno,Invierno,Invierno,Invierno,Luna Nueva
16646,2025-07-29,0.0,0,1,2,2,0,15.0,2.2,13.814286,...,N,0.0,0.0,0.0,0.0,Invierno,Invierno,Invierno,Invierno,Luna Nueva
16647,2025-07-30,0.0,0,1,2,2,0,18.7,4.8,14.871429,...,N,0.0,0.0,0.0,0.0,Invierno,Invierno,Invierno,Invierno,Luna Nueva

In [58]:
## Separamos el dataset en conjunto de entrenamiento y prueba
merged_preliminar_X_df = merged_preliminar_df.drop(columns=['manana_llueve'])
merged_preliminar_y_df = merged_preliminar_df['manana_llueve']

# Usamos 80% para entrenamiento y 20% para prueba, usando scikit-learn
entrenamiento_X_df, prueba_X_df, entrenamiento_y_df, prueba_y_df = sk.model_selection.train_test_split(
    merged_preliminar_X_df, merged_preliminar_y_df,
    test_size=0.2,
    random_state=13,
    shuffle=True,
    stratify=merged_preliminar_y_df
)
# Reunimos nuevamente los conjuntos de entrenamiento y prueba
entrenamiento_df = pd.concat([entrenamiento_X_df, entrenamiento_y_df], axis=1).reset_index(drop=True)
prueba_df = pd.concat([prueba_X_df, prueba_y_df], axis=1).reset_index(drop=True)

print(f"Tamaño del conjunto de entrenamiento: {entrenamiento_df.shape}")
print(f"Tamaño del conjunto de prueba: {prueba_df.shape}")
# Verificamos que la proporción de la clase objetivo se mantuvo en ambos conjuntos
print("Proporción de la clase objetivo en el conjunto de entrenamiento:")
print(entrenamiento_df['manana_llueve'].value_counts(normalize=True))
print("Proporción de la clase objetivo en el conjunto de prueba:")
print(prueba_df['manana_llueve'].value_counts(normalize=True))

Tamaño del conjunto de entrenamiento: (13318, 32)
Tamaño del conjunto de prueba: (3330, 32)
Proporción de la clase objetivo en el conjunto de entrenamiento:
manana_llueve
0    0.779697
1    0.220303
Name: proportion, dtype: float64
Proporción de la clase objetivo en el conjunto de prueba:
manana_llueve
0    0.77958
1    0.22042
Name: proportion, dtype: float64

In [59]:
## Ahora sí, podemos categorizar las variables que lo requieren, usando los datos del conjunto de entrenamiento para definir los umbrales
# Lluvia
# Calculamos el promedio de días lluviosos en el conjunto de entrenamiento
promedio_dias_lluviosos = entrenamiento_df['dia_lluvioso'].mean()
print(f"Promedio de días lluviosos en el conjunto de entrenamiento: {promedio_dias_lluviosos}")
# Para semana_lluviosa, quincena_lluviosa y mes_lluviosa, marcamos 1 si la cantidad de días lluviosos es mayor o igual al promedio, y 0 si es menor
entrenamiento_df['semana_lluviosa'] = (entrenamiento_df['semana_lluviosa'] >= promedio_dias_lluviosos * 7).astype(int)
entrenamiento_df['quincena_lluviosa'] = (entrenamiento_df['quincena_lluviosa'] >= promedio_dias_lluviosos * 15).astype(int)
entrenamiento_df['mes_lluvioso'] = (entrenamiento_df['mes_lluvioso'] >= promedio_dias_lluviosos * 30).astype(int)

# Temperatura
# Reemplazamos los valores NaN de temperatura por la media de cada columna del conjunto de entrenamiento
temp_max_promedio = entrenamiento_df['temp_max'].mean()
temp_min_promedio = entrenamiento_df['temp_min'].mean()
entrenamiento_df.fillna({'temp_max': temp_max_promedio, 'temp_max_semana': temp_max_promedio, 'temp_max_quincena': temp_max_promedio, 'temp_max_mes': temp_max_promedio}, inplace=True)
entrenamiento_df.fillna({'temp_min': temp_min_promedio, 'temp_min_semana': temp_min_promedio, 'temp_min_quincena': temp_min_promedio, 'temp_min_mes': temp_min_promedio}, inplace=True)
# Calculamos la temperatura promedio diaria
entrenamiento_df['temp_promedio_dia'] = (entrenamiento_df['temp_max'] + entrenamiento_df['temp_min']) / 2
entrenamiento_df['temp_promedio_semana'] = (entrenamiento_df['temp_max_semana'] + entrenamiento_df['temp_min_semana']) / 2
entrenamiento_df['temp_promedio_quincena'] = (entrenamiento_df['temp_max_quincena'] + entrenamiento_df['temp_min_quincena']) / 2
entrenamiento_df['temp_promedio_mes'] = (entrenamiento_df['temp_max_mes'] + entrenamiento_df['temp_min_mes']) / 2 
# Calculamos los umbrales para categorizar la temperatura
max_temp = entrenamiento_df['temp_promedio_dia'].max()
min_temp = entrenamiento_df['temp_promedio_dia'].min()
umbral_alta = min_temp + (max_temp - min_temp) * 2 / 3
umbral_baja = min_temp + (max_temp - min_temp) * 1 / 3
# Creamos funcion para categorizar la temperatura según umbrales en 'Baja', 'Media' y 'Alta'
def categorizar_temperatura(temp):
    if temp < umbral_baja:
        return 'Baja'
    elif umbral_baja <= temp < umbral_alta:
        return 'Media'
    else:
        return 'Alta'
# La aplicamos al dataframe y aseguramos que sea de tipo category de pandas
entrenamiento_df['temp_categoria_dia'] = entrenamiento_df['temp_promedio_dia'].apply(categorizar_temperatura).astype('category')
entrenamiento_df['temp_categoria_semana'] = entrenamiento_df['temp_promedio_semana'].apply(categorizar_temperatura).astype('category')
entrenamiento_df['temp_categoria_quincena'] = entrenamiento_df['temp_promedio_quincena'].apply(categorizar_temperatura).astype('category')
entrenamiento_df['temp_categoria_mes'] = entrenamiento_df['temp_promedio_mes'].apply(categorizar_temperatura).astype('category')

# Humedad relativa
# Reemplazamos los valores NaN de humedad relativa por la media de la columna del conjunto de entrenamiento
humedad_relativa_promedio = entrenamiento_df['humedad_relativa'].mean()
entrenamiento_df.fillna({'humedad_relativa': humedad_relativa_promedio, 'humedad_relativa_semana': humedad_relativa_promedio, 'humedad_relativa_quincena': humedad_relativa_promedio, 'humedad_relativa_mes': humedad_relativa_promedio}, inplace=True)
# Calculamos los umbrales para categorizar la humedad relativa en 'Baja', 'Media' y 'Alta'
max_humedad = entrenamiento_df['humedad_relativa'].max()
min_humedad = entrenamiento_df['humedad_relativa'].min()
umbral_alta_hum = min_humedad + (max_humedad - min_humedad) * 2 / 3
umbral_baja_hum = min_humedad + (max_humedad - min_humedad) * 1 / 3
# Creamos funcion para categorizar la humedad relativa en 'Baja', 'Media' y 'Alta'
def categorizar_humedad(hum):
    if hum < umbral_baja_hum:
        return 'Baja'
    elif umbral_baja_hum <= hum < umbral_alta_hum:
        return 'Media'
    else:
        return 'Alta'
# La aplicamos al dataframe y aseguramos que sea de tipo category de pandas
entrenamiento_df['humedad_categoria_dia'] = entrenamiento_df['humedad_relativa'].apply(categorizar_humedad).astype('category')
entrenamiento_df['humedad_categoria_semana'] = entrenamiento_df['humedad_relativa_semana'].apply(categorizar_humedad).astype('category')
entrenamiento_df['humedad_categoria_quincena'] = entrenamiento_df['humedad_relativa_quincena'].apply(categorizar_humedad).astype('category')
entrenamiento_df['humedad_categoria_mes'] = entrenamiento_df['humedad_relativa_mes'].apply(categorizar_humedad).astype('category')

# Viento
# Reemplazamos los valores NaN de viento por la moda del mes correspondiente (usando el conjunto de entrenamiento)
# Para ello, extraemos el mes de la fecha y usamos groupby para obtener la moda por mes
entrenamiento_df['mes'] = entrenamiento_df['fecha'].dt.month
moda_viento_por_mes = entrenamiento_df.groupby('mes')['direccion_viento'].agg(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
# Consideramos también mes de la semana, quincena y mes como la moda del mes
entrenamiento_df['mes_semana'] = entrenamiento_df['mes'].rolling(window=7, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
entrenamiento_df['mes_quincena'] = entrenamiento_df['mes'].rolling(window=15, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
entrenamiento_df['mes_mes'] = entrenamiento_df['mes'].rolling(window=30, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
# Función para reemplazar NaN por la moda del mes
def reemplazar_viento_por_moda(row):
    # Si no es NaN en ninguna de las columnas de dirección del viento, no hacemos nada
    if not pd.isna(row['direccion_viento']) and not pd.isna(row['direccion_viento_semana']) and not pd.isna(row['direccion_viento_quincena']) and not pd.isna(row['direccion_viento_mes']):
        return row
    # Si es NaN en direccion_viento, lo reemplazamos por la moda del mes
    else:
        if pd.isna(row['direccion_viento']):
            row['direccion_viento'] = moda_viento_por_mes[row['mes']]
        if pd.isna(row['direccion_viento_semana']):
            row['direccion_viento_semana'] = moda_viento_por_mes[row['mes_semana']]
        if pd.isna(row['direccion_viento_quincena']):
            row['direccion_viento_quincena'] = moda_viento_por_mes[row['mes_quincena']]
        if pd.isna(row['direccion_viento_mes']):
            row['direccion_viento_mes'] = moda_viento_por_mes[row['mes_mes']]
        return row

# Aplicamos la función al dataframe
entrenamiento_df = entrenamiento_df.apply(reemplazar_viento_por_moda, axis=1)
# Eliminamos las columnas auxiliares de mes
entrenamiento_df.drop(columns=['mes', 'mes_semana', 'mes_quincena', 'mes_mes'], inplace=True)
# Aseguramos que categoria sea de tipo category de pandas
entrenamiento_df['direccion_viento'] = entrenamiento_df['direccion_viento'].astype('category')

# Truenos
# Reemplazamos los valores NaN de hay_truenos por 0 (no hubo truenos)
entrenamiento_df['hay_truenos'] = entrenamiento_df['hay_truenos'].fillna(0).astype(int)
entrenamiento_df['hay_truenos_semana'] = entrenamiento_df['hay_truenos_semana'].fillna(0).astype(int)
entrenamiento_df['hay_truenos_quincena'] = entrenamiento_df['hay_truenos_quincena'].fillna(0).astype(int)
entrenamiento_df['hay_truenos_mes'] = entrenamiento_df['hay_truenos_mes'].fillna(0).astype(int)

# Imprimimos las filas con valores NaN en el conjunto de entrenamiento para verificar que no haya quedado ninguno
# Contamos los valores NaN en el conjunto de entrenamiento para verificar que no haya quedado ninguno
print("Valores NaN en el conjunto de entrenamiento después de la imputación:")
print(entrenamiento_df.isna().sum())
entrenamiento_df

Promedio de días lluviosos en el conjunto de entrenamiento: 0.2216549031386094
Valores NaN en el conjunto de entrenamiento después de la imputación:
fecha                         0
mm_lluvia                     0
dia_lluvioso                  0
semana_lluviosa               0
quincena_lluviosa             0
mes_lluvioso                  0
temp_max                      0
temp_min                      0
temp_max_semana               0
temp_min_semana               0
temp_max_quincena             0
temp_min_quincena             0
temp_max_mes                  0
temp_min_mes                  0
humedad_relativa              0
humedad_relativa_semana       0
humedad_relativa_quincena     0
humedad_relativa_mes          0
direccion_viento              0
direccion_viento_semana       0
direccion_viento_quincena     0
direccion_viento_mes          0
hay_truenos                   0
hay_truenos_semana            0
hay_truenos_quincena          0
hay_truenos_mes               0
estacion                      0
estacion_semana               0
estacion_quincena             0
estacion_mes                  0
fase_lunar                    0
manana_llueve                 0
temp_promedio_dia             0
temp_promedio_semana          0
temp_promedio_quincena        0
temp_promedio_mes             0
temp_categoria_dia            0
temp_categoria_semana         0
temp_categoria_quincena       0
temp_categoria_mes            0
humedad_categoria_dia         0
humedad_categoria_semana      0
humedad_categoria_quincena    0
humedad_categoria_mes         0
dtype: int64

,fecha,mm_lluvia,dia_lluvioso,semana_lluviosa,quincena_lluviosa,mes_lluvioso,temp_max,temp_min,temp_max_semana,temp_min_semana,...,temp_promedio_quincena,temp_promedio_mes,temp_categoria_dia,temp_categoria_semana,temp_categoria_quincena,temp_categoria_mes,humedad_categoria_dia,humedad_categoria_semana,humedad_categoria_quincena,humedad_categoria_mes
0,1990-10-30,0.0,0,1,0,1,22.5,18.6,23.214286,15.271429,...,17.936667,17.288333,Media,Media,Media,Media,Alta,Alta,Alta,Media
1,1989-05-29,0.0,0,0,0,0,19.8,9.0,18.142857,8.871429,...,15.033333,14.286667,Media,Media,Media,Media,Media,Media,Media,Media
2,2004-10-10,0.0,0,1,0,0,16.0,13.8,18.228571,10.371429,...,14.320000,13.820000,Media,Media,Media,Media,Alta,Media,Media,Media
3,1984-07-04,0.5,0,1,1,1,11.4,4.6,15.228571,8.142857,...,10.576667,9.958333,Baja,Baja,Baja,Baja,Alta,Media,Alta,Alta
4,2002-01-02,0.0,0,0,0,0,25.0,19.0,27.200000,18.985714,...,22.183333,20.720000,Media,Alta,Media,Media,Alta,Media,Media,Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13313,1999-03-11,0.0,0,0,0,0,22.0,19.0,27.314286,20.028571,...,23.620000,23.293333,Media,Alta,Alta,Alta,Media,Media,Alta,Alta
13314,1997-07-16,0.0,0,1,0,0,14.0,3.0,15.314286,8.171429,...,10.606667,10.285000,Baja,Baja,Baja,Baja,Media,Alta,Alta,Media
13315,1982-04-24,0.3,0,1,1,1,22.2,15.2,21.571429,14.557143,...,17.970000,19.003333,Media,Media,Media,Media,Alta,Alta,Media,Media
13316,1983-06-21,1.3,1,1,1,1,14.8,11.6,16.114286,10.285714,...,10.556667,10.436667,Media,Media,Baja,Baja,Alta,Alta,Alta,Alta
13317,2022-05-29,0.0,0,1,1,0,11.6,6.0,15.714286,8.800000,...,12.543333,13.465000,Baja,Baja,Baja,Media,Media,Alta,Alta,Alta

In [60]:
# Lluvia
prueba_df['semana_lluviosa'] = (prueba_df['semana_lluviosa'] >= promedio_dias_lluviosos * 7).astype(int)
prueba_df['quincena_lluviosa'] = (prueba_df['quincena_lluviosa'] >= promedio_dias_lluviosos * 15).astype(int)
prueba_df['mes_lluvioso'] = (prueba_df['mes_lluvioso'] >= promedio_dias_lluviosos * 30).astype(int)

# Temperatura
prueba_df.fillna({'temp_max': temp_max_promedio, 'temp_max_semana': temp_max_promedio, 'temp_max_quincena': temp_max_promedio, 'temp_max_mes': temp_max_promedio}, inplace=True)
prueba_df.fillna({'temp_min': temp_min_promedio, 'temp_min_semana': temp_min_promedio, 'temp_min_quincena': temp_min_promedio, 'temp_min_mes': temp_min_promedio}, inplace=True)
prueba_df['temp_promedio_dia'] = (prueba_df['temp_max'] + prueba_df['temp_min']) / 2
prueba_df['temp_promedio_semana'] = (prueba_df['temp_max_semana'] + prueba_df['temp_min_semana']) / 2
prueba_df['temp_promedio_quincena'] = (prueba_df['temp_max_quincena'] + prueba_df['temp_min_quincena']) / 2
prueba_df['temp_promedio_mes'] = (prueba_df['temp_max_mes'] + prueba_df['temp_min_mes']) / 2
prueba_df['temp_categoria_dia'] = prueba_df['temp_promedio_dia'].apply(categorizar_temperatura).astype('category')
prueba_df['temp_categoria_semana'] = prueba_df['temp_promedio_semana'].apply(categorizar_temperatura).astype('category')
prueba_df['temp_categoria_quincena'] = prueba_df['temp_promedio_quincena'].apply(categorizar_temperatura).astype('category')
prueba_df['temp_categoria_mes'] = prueba_df['temp_promedio_mes'].apply(categorizar_temperatura).astype('category')

# Humedad relativa
prueba_df.fillna({'humedad_relativa': humedad_relativa_promedio, 'humedad_relativa_semana': humedad_relativa_promedio, 'humedad_relativa_quincena': humedad_relativa_promedio, 'humedad_relativa_mes': humedad_relativa_promedio}, inplace=True)
prueba_df['humedad_categoria_dia'] = prueba_df['humedad_relativa'].apply(categorizar_humedad).astype('category')
prueba_df['humedad_categoria_semana'] = prueba_df['humedad_relativa_semana'].apply(categorizar_humedad).astype('category')
prueba_df['humedad_categoria_quincena'] = prueba_df['humedad_relativa_quincena'].apply(categorizar_humedad).astype('category')
prueba_df['humedad_categoria_mes'] = prueba_df['humedad_relativa_mes'].apply(categorizar_humedad).astype('category')

# Viento
prueba_df['mes'] = prueba_df['fecha'].dt.month
prueba_df['mes_semana'] = prueba_df['mes'].rolling(window=7, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
prueba_df['mes_quincena'] = prueba_df['mes'].rolling(window=15, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
prueba_df['mes_mes'] = prueba_df['mes'].rolling(window=30, min_periods=1).apply(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
prueba_df = prueba_df.apply(reemplazar_viento_por_moda, axis=1)
prueba_df.drop(columns=['mes', 'mes_semana', 'mes_quincena', 'mes_mes'], inplace=True)
prueba_df['direccion_viento'] = prueba_df['direccion_viento'].astype('category')

# Truenos
prueba_df['hay_truenos'] = prueba_df['hay_truenos'].fillna(0).astype(int)
prueba_df['hay_truenos_semana'] = prueba_df['hay_truenos_semana'].fillna(0).astype(int)
prueba_df['hay_truenos_quincena'] = prueba_df['hay_truenos_quincena'].fillna(0).astype(int)
prueba_df['hay_truenos_mes'] = prueba_df['hay_truenos_mes'].fillna(0).astype(int)

print("Valores NaN en el conjunto de prueba después de la imputación:")
print(prueba_df.isna().sum())
prueba_df

Valores NaN en el conjunto de prueba después de la imputación:
fecha                         0
mm_lluvia                     0
dia_lluvioso                  0
semana_lluviosa               0
quincena_lluviosa             0
mes_lluvioso                  0
temp_max                      0
temp_min                      0
temp_max_semana               0
temp_min_semana               0
temp_max_quincena             0
temp_min_quincena             0
temp_max_mes                  0
temp_min_mes                  0
humedad_relativa              0
humedad_relativa_semana       0
humedad_relativa_quincena     0
humedad_relativa_mes          0
direccion_viento              0
direccion_viento_semana       0
direccion_viento_quincena     0
direccion_viento_mes          0
hay_truenos                   0
hay_truenos_semana            0
hay_truenos_quincena          0
hay_truenos_mes               0
estacion                      0
estacion_semana               0
estacion_quincena             0
estacion_mes                  0
fase_lunar                    0
manana_llueve                 0
temp_promedio_dia             0
temp_promedio_semana          0
temp_promedio_quincena        0
temp_promedio_mes             0
temp_categoria_dia            0
temp_categoria_semana         0
temp_categoria_quincena       0
temp_categoria_mes            0
humedad_categoria_dia         0
humedad_categoria_semana      0
humedad_categoria_quincena    0
humedad_categoria_mes         0
dtype: int64

,fecha,mm_lluvia,dia_lluvioso,semana_lluviosa,quincena_lluviosa,mes_lluvioso,temp_max,temp_min,temp_max_semana,temp_min_semana,...,temp_promedio_quincena,temp_promedio_mes,temp_categoria_dia,temp_categoria_semana,temp_categoria_quincena,temp_categoria_mes,humedad_categoria_dia,humedad_categoria_semana,humedad_categoria_quincena,humedad_categoria_mes
0,1980-08-08,0.0,0,1,0,0,16.0,5.5,14.371429,8.057143,...,10.676667,10.608333,Baja,Baja,Baja,Baja,Media,Alta,Media,Media
1,2020-12-27,0.0,0,0,0,0,26.4,19.4,25.985714,16.600000,...,21.076667,20.665000,Alta,Media,Media,Media,Alta,Media,Media,Media
2,2016-11-02,2.1,1,1,1,1,16.4,9.1,20.457143,11.685714,...,15.680000,16.116667,Media,Media,Media,Media,Alta,Media,Alta,Alta
3,2017-03-11,1.0,1,1,0,0,25.4,11.4,25.914286,15.657143,...,23.903333,24.390000,Media,Media,Alta,Alta,Media,Media,Media,Media
4,1999-04-14,0.0,0,1,1,1,24.2,11.0,20.500000,10.842857,...,16.693333,18.285000,Media,Media,Media,Media,Media,Media,Media,Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3325,2021-10-19,0.0,0,0,0,0,20.2,6.0,20.071429,9.500000,...,14.500000,14.650000,Media,Media,Media,Media,Media,Media,Media,Media
3326,1982-02-07,0.0,0,0,0,0,30.0,16.8,28.085714,16.742857,...,23.973333,22.490000,Alta,Media,Alta,Media,Media,Media,Media,Media
3327,2021-03-13,0.0,0,0,0,0,23.4,12.0,26.571429,15.671429,...,22.063333,22.023333,Media,Media,Media,Media,Media,Media,Media,Media
3328,1981-11-03,0.1,0,1,1,1,20.0,16.6,24.200000,16.914286,...,18.870000,15.706667,Media,Media,Media,Media,Alta,Alta,Media,Media
3329,2002-08-30,0.0,0,1,1,1,11.2,7.5,26.128571,14.714286,...,17.466667,14.011667,Baja,Media,Media,Media,Media,Media,Alta,Alta

In [61]:
# Nos quedamos solo con las columnas que nos interesan
columnas_interes_m1 = ['fecha', 'dia_lluvioso', 'temp_categoria_dia', 'humedad_categoria_dia', 'direccion_viento', 'estacion', 'manana_llueve']
columnas_interes_m2 = columnas_interes_m1 + ['hay_truenos', 'fase_lunar']

entrenamiento_final_m1_df = entrenamiento_df[columnas_interes_m1].copy()
prueba_final_m1_df = prueba_df[columnas_interes_m1].copy()

entrenamiento_final_m2_df = entrenamiento_df[columnas_interes_m2].copy()
prueba_final_m2_df = prueba_df[columnas_interes_m2].copy()

# Para modelos de Naive Bayes, creamos tambien versiones con distintos valores de nd (7, 15, 30) para las variables categóricas
# Modelo 1
columnas_interes_m1_7 = ['fecha', 'semana_lluviosa', 'temp_categoria_semana', 'humedad_categoria_semana', 'direccion_viento_semana', 'estacion_semana', 'manana_llueve']
columnas_interes_m1_15 = ['fecha', 'quincena_lluviosa', 'temp_categoria_quincena', 'humedad_categoria_quincena', 'direccion_viento_quincena', 'estacion_quincena', 'manana_llueve']
columnas_interes_m1_30 = ['fecha', 'mes_lluvioso', 'temp_categoria_mes', 'humedad_categoria_mes', 'direccion_viento_mes', 'estacion_mes', 'manana_llueve']

entrenamiento_final_m1_7_df = entrenamiento_df[columnas_interes_m1_7].copy()
prueba_final_m1_7_df = prueba_df[columnas_interes_m1_7].copy()

entrenamiento_final_m1_15_df = entrenamiento_df[columnas_interes_m1_15].copy()
prueba_final_m1_15_df = prueba_df[columnas_interes_m1_15].copy()

entrenamiento_final_m1_30_df = entrenamiento_df[columnas_interes_m1_30].copy()
prueba_final_m1_30_df = prueba_df[columnas_interes_m1_30].copy()

# Modelo 2 ?

In [62]:
entrenamiento_final_m1_30_df

,fecha,mes_lluvioso,temp_categoria_mes,humedad_categoria_mes,direccion_viento_mes,estacion_mes,manana_llueve
0,1990-10-30,1,Media,Media,SE,Primavera,0
1,1989-05-29,0,Media,Media,N,Otoño,0
2,2004-10-10,0,Media,Media,N,Primavera,0
3,1984-07-04,1,Baja,Alta,SE,Otoño,1
4,2002-01-02,0,Media,Media,S,Primavera,0
...,...,...,...,...,...,...,...
13313,1999-03-11,0,Alta,Alta,SE,Verano,0
13314,1997-07-16,0,Baja,Media,SE,Invierno,0
13315,1982-04-24,1,Media,Media,N,Otoño,0
13316,1983-06-21,1,Baja,Alta,N,Otoño,0
13317,2022-05-29,0,Media,Alta,N,Otoño,0

In [63]:
prueba_final_m1_df

,fecha,dia_lluvioso,temp_categoria_dia,humedad_categoria_dia,direccion_viento,estacion,manana_llueve
0,1980-08-08,0,Baja,Media,N,Invierno,0
1,2020-12-27,0,Alta,Alta,SE,Verano,0
2,2016-11-02,1,Media,Alta,W,Primavera,0
3,2017-03-11,1,Media,Media,N,Verano,0
4,1999-04-14,0,Media,Media,N,Otoño,1
...,...,...,...,...,...,...,...
3325,2021-10-19,0,Media,Media,SE,Primavera,0
3326,1982-02-07,0,Alta,Media,SE,Verano,1
3327,2021-03-13,0,Media,Media,SE,Verano,0
3328,1981-11-03,0,Media,Alta,SE,Primavera,1
3329,2002-08-30,0,Baja,Media,W,Invierno,1

In [64]:
def calcular_probabilidad(df, col, valor, clase, m):
    # Filtrar el DataFrame por la clase
    df_clase = df[df['manana_llueve'] == clase]
    cant_elementos = len(df_clase)
    p=1/len(df_clase[col].unique())
    # Calcular la probabilidad
    if(cant_elementos == 0):
        print("No hay elementos de la clase ", clase, " para calcular la probabilidad")
        return 0
    #Utilizamos m-estimador (e + m * p) / (n + m)
    return ((df_clase[col].value_counts().get(valor, 0) + m *p) / (cant_elementos + m))

In [65]:
def predecir_clase(fila, modelo, prob_iniciales):
    prob_clases = [1, 1]
    for i in range(2):
        for col in fila.index:
            if col != 'manana_llueve':
                valor = fila[col]
                # Buscar la probabilidad correspondiente en el modelo
                prob = None
                for item in modelo[i]:
                    if item[0] == col and item[1] == valor:
                        prob = item[2]
                        break
                prob_clases[i] *= prob
        # Multiplicamos por la probabilidad de la clase
        prob_clases[i] *= prob_iniciales[i]

    # Devolvemos la clase con mayor probabilidad
    if(prob_clases[0]>prob_clases[1]):
        return 0
    else:
        return 1

In [66]:
def encode(str):
    if str == 'Baja' or str == 'N' or str == "Verano":
        return 0
    elif str == 'Media' or str == 'NE' or str == 'Otoño':
        return 1
    elif str == 'Alta' or str == 'E' or str == 'Invierno':
        return 2
    elif str == 'SE' or str == 'Primavera':
        return 3
    elif str == 'S':
        return 4
    elif str == 'SW':
        return 5
    elif str == 'W':
        return 6
    elif str == 'NW':
        return 7
    elif str == 0 or str == 1:
        return int(str)

In [67]:
class NaiveBayes:
    def __init__(self, m=1):
        self.m = m
        self.modelo = [[], []]  # Lista para almacenar las probabilidades de cada clase
        self.prob_iniciales = [0, 0]  # Probabilidades iniciales de cada clase

    def fit(self, X, y):
        df=X.copy()
        df['manana_llueve']=y
        # Calcular las probabilidades iniciales de cada clase
        total_filas = len(df)
        self.prob_iniciales[0] = len(df[df['manana_llueve'] == 0]) / total_filas
        self.prob_iniciales[1] = 1-self.prob_iniciales[0]
        #Para cada clase, para cada columna, para cada valor posible, calcular la probabilidad y almacenarla
        for i in range(2):
            for col in df.columns:
                if col != 'fecha' and col != 'manana_llueve':
                    # Columnas categóricas
                    if df[col].dtype.name == 'category':
                        valores_posibles = df[col].cat.categories.tolist()
                    else:
                        # Columnas numéricas
                        valores_posibles = df[col].unique().tolist()
                    for valor in valores_posibles:
                        prob = calcular_probabilidad(df, col, valor, i, self.m)
                        self.modelo[i].append((col, valor, prob))

    def predict(self, X):
        # Predecir la clase para cada fila en X
        return X.apply(lambda fila: predecir_clase(fila, self.modelo, self.prob_iniciales), axis=1)

In [ ]:
m=1
valores_k=[2,3,4,5]


entrenamiento_NB_df = entrenamiento_final_m1_df.drop(columns=['fecha', "manana_llueve"]).copy()
y_entrenamiento_NB = entrenamiento_final_m1_df['manana_llueve']
prueba_NB_df = prueba_final_m1_df.drop(columns=['fecha', "manana_llueve"]).copy()
y_prueba_NB = prueba_final_m1_df['manana_llueve']

#convertir todos los atributos categóricos a tipo 'category' de pandas
for col in entrenamiento_NB_df.columns:
        entrenamiento_NB_df[col] = entrenamiento_NB_df[col].astype('category')

entrenamiento_NB_df = entrenamiento_NB_df.applymap(encode)
prueba_NB_df = prueba_NB_df.applymap(encode)



kf = KFold(n_splits=5, shuffle=True, random_state=24)
for k in valores_k:

    valores_f1= []
    valores_pres = []
    valores_rec = []
    print(f"Evaluando k={k}")
    
    # Particionamos los datos
    for train_index, val_index in kf.split(entrenamiento_NB_df):    
        X_train_fold = entrenamiento_NB_df.iloc[train_index]
        X_val_fold = entrenamiento_NB_df.iloc[val_index]
        y_train_fold = y_entrenamiento_NB.iloc[train_index]
        y_val_fold = y_entrenamiento_NB.iloc[val_index]

        selector = SelectKBest(chi2, k)
        selector.fit(X_train_fold, y_train_fold)
        
        # Aplicar selección a train y validation de este fold
        X_train_selec = X_train_fold.iloc[:, selector.get_support()]
        X_val_selec = X_val_fold.iloc[:, selector.get_support()]
        
        # Entrenamos el modelo
        modelo_nb_cv = NaiveBayes(m)
        modelo_nb_cv.fit(X_train_selec, y_train_fold)

        # Evaluamos
        predicciones_cv = modelo_nb_cv.predict(X_val_selec)

        valores_pres.append(precision_score(y_val_fold, predicciones_cv))
        valores_rec.append(recall_score(y_val_fold, predicciones_cv))
        valores_f1.append(f1_score(y_val_fold, predicciones_cv))

        #print(f"Precisión: {precision_cv}")
        #print(f"Recall: {recall_cv}")
        #print(f"F1-Score: {f1_cv}")
        #print("----")
    precision_promedio = np.mean(valores_pres)
    recall_promedio = np.mean(valores_rec)
    f1_promedio = np.mean(valores_f1)
    print(f"Precisión promedio: {precision_promedio}")
    print(f"Recall promedio: {recall_promedio}")
    print(f"F1-Score promedio: {f1_promedio}")
    print("====")

C:\Users\D967036\AppData\Local\Temp\ipykernel_14992\930474884.py:14: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  entrenamiento_NB_df = entrenamiento_NB_df.applymap(encode)
C:\Users\D967036\AppData\Local\Temp\ipykernel_14992\930474884.py:15: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  prueba_NB_df = prueba_NB_df.applymap(encode)

Evaluando k=2
Columnas seleccionadas: ['dia_lluvioso', 'direccion_viento']
Precisión promedio: 0.4921515984015984
Recall promedio: 0.08222781858265485
F1-Score promedio: 0.1382182267322262
====
Evaluando k=3
Columnas seleccionadas: ['dia_lluvioso', 'temp_categoria_dia', 'direccion_viento']
Precisión promedio: 0.4659934563269362
Recall promedio: 0.10250712978916998
F1-Score promedio: 0.16650007514705958
====
Evaluando k=4
Columnas seleccionadas: ['dia_lluvioso', 'temp_categoria_dia', 'humedad_categoria_dia', 'direccion_viento']
Precisión promedio: 0.43734924168293354
Recall promedio: 0.10039722618344675
F1-Score promedio: 0.16313237763031826
====
Evaluando k=5
Columnas seleccionadas: ['dia_lluvioso', 'temp_categoria_dia', 'humedad_categoria_dia', 'direccion_viento', 'estacion']
Precisión promedio: 0.44410961888683664
Recall promedio: 0.10828827130148673
F1-Score promedio: 0.17375263691453185
====

In [ ]:
# Implementación Naive Bayes

entrenamiento_NB_df = entrenamiento_final_m1_df.drop(columns=['fecha']).copy()
prueba_NB_df = entrenamiento_final_m1_df.drop(columns=['fecha']).copy()


#convertir todos los atributos categóricos a tipo 'category' de pandas
for col in entrenamiento_NB_df.columns:
    if col != 'fecha' and col != 'manana_llueve':
        entrenamiento_NB_df[col] = entrenamiento_NB_df[col].astype('category')

# Modelo es una lista de 2 listas, la primera corresponde a la clase 0 y la segunda a la clase 1. 
# Cada sublista contiene tuplas (nombre columna, valor posible, probabilidad)
modelo = []

# m para m-estimador
m = 10

# Probabilidades P(Vj) - Iniciales para cada clase
prob0 = len(entrenamiento_NB_df[entrenamiento_NB_df['manana_llueve'] == 0]) / len(entrenamiento_NB_df)
prob1 = 1 - prob0
prob_iniciales = [prob0, prob1]
print(f"Probabilidades iniciales: {prob_iniciales}")

#Para cada clase objetivo recorro todas las columnas y sus valores posibles para calcular P(Atributo=valor|Clase)
for i in range(2):
    modelo.append([])
    for col in entrenamiento_NB_df.columns:
        if col != 'fecha' and col != 'manana_llueve':
            # Columnas categóricas
            if entrenamiento_NB_df[col].dtype.name == 'category':
                valores_posibles = entrenamiento_NB_df[col].cat.categories.tolist()
            else:
                # Columnas numéricas
                valores_posibles = entrenamiento_NB_df[col].unique().tolist()
            for valor in valores_posibles:
                prob = calcular_probabilidad(entrenamiento_NB_df, col, valor, i, m)
                modelo[i].append((col, valor, prob))

# Imprimimos el modelo
for i in range(2):
    print(f"Probabilidades para la clase {i}:")
    for item in modelo[i]:
        print(item)
    print("----")

y_true = []
y_pred = []
for i in prueba_NB_df.index:
    fila = prueba_NB_df.loc[i]
    clase_pred = predecir_clase(fila, modelo, prob_iniciales)
    #print(f"Fila {i}: Real {fila['manana_llueve']} Predicha = {clase_pred}")
    y_true.append(fila['manana_llueve'])
    y_pred.append(clase_pred)


# Evaluamos el modelo
precision = sk.metrics.precision_score(y_true, y_pred)
recall = sk.metrics.recall_score(y_true, y_pred)
print(f"Precisión: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Probabilidades iniciales: [0.7796966511488211, 0.22030334885117886]
Probabilidades para la clase 0:
('dia_lluvioso', 0, np.float64(0.8253800269386184))
('dia_lluvioso', 1, np.float64(0.17461997306138158))
('temp_categoria_dia', 'Alta', np.float64(0.12847155410172534))
('temp_categoria_dia', 'Baja', np.float64(0.2848117503688025))
('temp_categoria_dia', 'Media', np.float64(0.5867166955294721))
('humedad_categoria_dia', 'Alta', np.float64(0.3961259701109614))
('humedad_categoria_dia', 'Baja', np.float64(0.0662241036495414))
('humedad_categoria_dia', 'Media', np.float64(0.5376499262394971))
('direccion_viento', 'E', np.float64(0.08083990763902252))
('direccion_viento', 'N', np.float64(0.29278910910140465))
('direccion_viento', 'NE', np.float64(0.08978737733307678))
('direccion_viento', 'NW', np.float64(0.04341446988647297))
('direccion_viento', 'S', np.float64(0.1093178756975178))
('direccion_viento', 'SE', np.float64(0.27220030786992494))
('direccion_viento', 'SW', np.float64(0.06111699057148355))
('direccion_viento', 'W', np.float64(0.05053396190109679))
('estacion', 'Invierno', np.float64(0.2562536078506831))
('estacion', 'Otoño', np.float64(0.2561573984991341))
('estacion', 'Primavera', np.float64(0.2404752741966519))
('estacion', 'Verano', np.float64(0.2471137194535309))
----
Probabilidades para la clase 1:
('dia_lluvioso', 0, np.float64(0.6103940217391305))
('dia_lluvioso', 1, np.float64(0.38960597826086957))
('temp_categoria_dia', 'Alta', np.float64(0.18897192028985507))
('temp_categoria_dia', 'Baja', np.float64(0.18285778985507248))
('temp_categoria_dia', 'Media', np.float64(0.6281702898550724))
('humedad_categoria_dia', 'Alta', np.float64(0.5045289855072463))
('humedad_categoria_dia', 'Baja', np.float64(0.04698822463768116))
('humedad_categoria_dia', 'Media', np.float64(0.44848278985507245))
('direccion_viento', 'E', np.float64(0.1383322010869565))
('direccion_viento', 'N', np.float64(0.2918648097826087))
('direccion_viento', 'NE', np.float64(0.1383322010869565))
('direccion_viento', 'NW', np.float64(0.022503396739130436))
('direccion_viento', 'S', np.float64(0.06394361413043478))
('direccion_viento', 'SE', np.float64(0.3003566576086957))
('direccion_viento', 'SW', np.float64(0.025900135869565216))
('direccion_viento', 'W', np.float64(0.018766983695652172))
('estacion', 'Invierno', np.float64(0.24711277173913043))
('estacion', 'Otoño', np.float64(0.26919157608695654))
('estacion', 'Primavera', np.float64(0.24031929347826086))
('estacion', 'Verano', np.float64(0.24337635869565216))
----
Precisión: 0.4466
Recall: 0.1026

In [ ]:
y_true = []
y_pred = []
for i in prueba_final_m1_df.index:
    fila = prueba_final_m1_df.loc[i]
    clase_pred = predecir_clase(fila, modelo)
    #print(f"Fila {i}: Real {fila['manana_llueve']} Predicha = {clase_pred}")
    y_true.append(fila['manana_llueve'])
    y_pred.append(clase_pred)


# Evaluamos el modelo
precision = sk.metrics.precision_score(y_true, y_pred)
recall = sk.metrics.recall_score(y_true, y_pred)
print(f"Precisión: {precision:.4f}")
print(f"Recall: {recall:.4f}")

TypeError: predecir_clase() missing 1 required positional argument: 'prob_iniciales'

In [ ]:
#print(entrenamiento_final_m1_df.head())
#print(f"\nTipos de datos: {entrenamiento_final_m1_df.dtypes}")
#entrenamiento_final_m1_df['dia_lluvioso'] = entrenamiento_final_m1_df['dia_lluvioso'].astype('category')
#entrenamiento_final_m1_df['manana_llueve'] = entrenamiento_final_m1_df['manana_llueve'].astype('category')

In [ ]:
##Duplicar filas del df que tengan manana_llueve = 1 para balancear el dataset
entrenamiento_encoded['manana_llueve'] = entrenamiento_final_m1_df['manana_llueve']
# Duplicar filas que tengan manana_llueve = 1 2 veces
entrenamiento_encoded = pd.concat([entrenamiento_encoded, entrenamiento_encoded[entrenamiento_encoded['manana_llueve'] == 1]] * 2, ignore_index=True)

prob0 = len(entrenamiento_encoded[entrenamiento_encoded['manana_llueve'] == 0]) / len(entrenamiento_encoded)
prob1 = 1 - prob0

print(f"Probabilidades iniciales después de balancear: {[prob0, prob1]}")

entrenamiento_encoded_mas = entrenamiento_encoded.drop(columns=['manana_llueve']).copy()

In [ ]:
entrenamiento_encoded_NB_df = entrenamiento_NB_df.drop(columns=['fecha', 'manana_llueve']).copy()
y_entrenamiento_NB_df = entrenamiento_NB_df['manana_llueve'].copy()
prueba_encoded_NB_df = prueba_NB_df.drop(columns=['fecha', 'manana_llueve']).copy()
y_prueba_NB_df = prueba_NB_df['manana_llueve'].copy()

def encode(str):
    if str == 'Baja' or str == 'N' or str == "Verano":
        return 0
    elif str == 'Media' or str == 'NE' or str == 'Otoño':
        return 1
    elif str == 'Alta' or str == 'E' or str == 'Invierno':
        return 2
    elif str == 'SE' or str == 'Primavera':
        return 3
    elif str == 'S':
        return 4
    elif str == 'SW':
        return 5
    elif str == 'W':
        return 6
    elif str == 'NW':
        return 7
    elif str == 0 or str == 1:
        return int(str)


print(f"\nTipos de datos: {entrenamiento_encoded_NB_df.dtypes}")
print(f"\nTipos de datos: {entrenamiento_encoded_NB_df.head()}")
#Aplicamos la función de encoding a todas las columnas categóricas
for col in entrenamiento_encoded_NB_df.columns:
    if entrenamiento_encoded_NB_df[col].dtype.name == 'category':
        entrenamiento_encoded_NB_df[col] = entrenamiento_encoded_NB_df[col].apply(encode)
        prueba_encoded_NB_df[col] = prueba_encoded_NB_df[col].apply(encode)

print(f"\nTipos de datos: {entrenamiento_encoded_NB_df.dtypes}")
print(f"\nTipos de datos: {y_entrenamiento_NB_df.dtypes}")
print(f"\nTipos de datos: {y_entrenamiento_NB_df.head()}")

In [ ]:
# Naive Bayes con CategoricalNB
from sklearn.naive_bayes import CategoricalNB

# Creamos el modelo
nb_model = CategoricalNB()
# Entrenamos el modelo
nb_model.fit(entrenamiento_encoded_NB_df, y_entrenamiento_NB_df)
# Hacemos predicciones
predicciones = nb_model.predict(prueba_encoded_NB_df)
# Evaluamos el modelo
precision_nb = precision_score(y_prueba_NB_df, predicciones)
recall_nb = recall_score(y_prueba_NB_df, predicciones)
f1_nb = f1_score(y_prueba_NB_df, predicciones)
accuracy_nb = accuracy_score(y_prueba_NB_df, predicciones)

print(f"\nResultados CategoricalNB:")
print(f"Precisión: {precision_nb:.4f}")
print(f"Recall: {recall_nb:.4f}")
print(f"F1-Score: {f1_nb:.4f}")
print(f"Accuracy: {accuracy_nb:.4f}")